stages:
  - test

run_hdxcli_tests:
  stage: test
  image: python:3.11
  variables:
    PYTHONPATH: "$CI_PROJECT_DIR/src"
  before_script:
    # Install uv
    - pip install uv
    # Install project dependencies using uv
    - uv pip install

    # Install Poetry
    #- pip install poetry
    # Install project dependencies using Poetry
    #- poetry install
  script:
    # Run tests
    - uv run pytest -v
    #- poetry run python -m pytest -v
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
